[WIP] Parser
mkaput/janus pull request #23
Opened 2017-01-24 10:08 UTC by Kotwic4

fix #8, fix #9

2017-01-24 20:31 UTC, mkaput commented on src/Language/Janus/Parser/Grammar.hs
> +  return (Block b)
```haskell
block = braces (many statement) >>= return . Block
```

2017-01-24 21:10 UTC, Kotwic4 commented on src/Language/Janus/Parser/Grammar.hs
> +  return (Block b)
można i można też podobnie zrobić z path, zapomniałem o tym że można zrobić tą .

2017-01-24 23:04 UTC, Kotwic4 commented
Gotowe

2017-01-25 08:21 UTC, mkaput commented
![obraz](https://cloud.githubusercontent.com/assets/3450050/22282934/a918b6fa-e2df-11e6-8214-6e19b80dceef.png)

2017-01-25 08:22 UTC, mkaput requested changes
coś nie działa

2017-01-25 08:30 UTC, Kotwic4 commented
Nie działa bo zgodnie z definicja musi być srednik :P 
expr_stmt : expr ";"

2017-01-25 17:20 UTC, merged